FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

# Copy everything .dockerignore ignores the rest of the files
COPY ./netcore ./

# Restore files from the Api folder which affects all other folders
WORKDIR /app/Api
RUN dotnet restore

# Build production files
RUN dotnet publish -c Release -o out
# RUN mkdir -p out

#Revert back to the default directory
WORKDIR /app

# Build runtime image
FROM mcr.microsoft.com/dotnet/runtime:5.0
WORKDIR /app

# install System.Drawing native dependencies
# RUN apt-get update \
#     && apt-get install -y --allow-unauthenticated \
#         libc6-dev \
#         libgdiplus \
#         libx11-dev \
#      && rm -rf /var/lib/apt/lists/*

COPY --from=build-env /app/Api/out .

# Copy botdetect.xml for botdetect captcha testing
# RUN mkdir Api
COPY --from=build-env /app/Api/botdetect.xml ./

# Copy json file for seeding 
RUN mkdir -p ../Persistence/data/
RUN mkdir -p ../Infrastructure/data/
RUN mkdir -p ../Infrastructure/Implementation/Email/Templates/

COPY --from=build-env /app/Persistence/data ../Persistence/data
COPY --from=build-env /app/Infrastructure/Implementation/Email/Templates ../Infrastructure/Implementation/Email/Templates

# RUN date --set = date -d "1 hour"  ..

# expose port
EXPOSE 5000

ENTRYPOINT ["dotnet","Api.dll"]

